defaults:
  - dataset: kitti
  - model: idisc_r101
  - _self_
  - finetune: image
  - experiment: eval_idisc_image
  - paths: cluster
  - tracking: none

run:
  task: eval
  exp_id: eval-idisc
  name: ${run.exp_id}
  dataset_mode: image

method:
  idr_source: afp
  sam_mode: null
  prompt:
    mode: null
    classes: []

tags: []

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
